name: 🔌 AI Provider Issue
description: Report issues with AI provider integrations
title: "[Provider]: "
labels: ["provider", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting an AI provider issue! This helps us improve our integrations.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm the following before submitting
      options:
        - label: I have verified my API key is valid and has sufficient credits
          required: true
        - label: I have tested with other providers (if available) to isolate the issue
          required: true
        - label: I have checked the provider's status page for outages
          required: true

  - type: dropdown
    id: provider
    attributes:
      label: AI Provider
      description: Which AI provider is experiencing issues?
      options:
        - OpenAI
        - Anthropic (Claude)
        - Google (Gemini)
        - OpenRouter
        - Cohere
        - HuggingFace
        - Local Provider
        - Other (please specify)
    validations:
      required: true

  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What type of issue are you experiencing?
      options:
        - Authentication/API Key Issues
        - Request Timeout/Slow Response
        - Error Responses from Provider
        - Unexpected Output/Quality Issues
        - Rate Limiting Issues
        - Configuration Problems
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Issue Description
      description: Describe the issue you're experiencing with the provider
      placeholder: Provide a clear description of the problem
    validations:
      required: true

  - type: input
    id: model
    attributes:
      label: Model Used
      description: Which specific model were you using?
      placeholder: e.g., gpt-4, claude-3-sonnet, gemini-pro
    validations:
      required: false

  - type: textarea
    id: error-message
    attributes:
      label: Error Message
      description: Exact error message received (remove any sensitive information)
      placeholder: Paste the error message here
      render: text
    validations:
      required: false

  - type: textarea
    id: request-details
    attributes:
      label: Request Details
      description: Details about the request that failed
      placeholder: |
        - Template used: 
        - Input text length: 
        - Expected behavior: 
        - Actual behavior:
    validations:
      required: false

  - type: dropdown
    id: frequency
    attributes:
      label: Issue Frequency
      description: How often does this issue occur?
      options:
        - Always (100% of the time)
        - Frequently (more than 50% of the time)
        - Sometimes (less than 50% of the time)
        - Rarely (only happened once or twice)
    validations:
      required: true

  - type: textarea
    id: configuration
    attributes:
      label: Provider Configuration
      description: Your provider configuration (remove sensitive information like API keys)
      placeholder: |
        - API endpoint: 
        - Custom headers: 
        - Timeout settings: 
        - Other relevant settings:
      render: text
    validations:
      required: false

  - type: textarea
    id: workaround
    attributes:
      label: Workaround
      description: Have you found any workarounds for this issue?
      placeholder: Describe any temporary solutions you've found
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other relevant information
      placeholder: Network conditions, browser settings, etc.
    validations:
      required: false
